[package]
name = "zkevm-circuits"
version = "0.1.0"
authors = ["therealyingtong <yingtong@z.cash>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-std = { version = "0.3", features = ["print-trace"] }
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_02_02" }
num = "0.4"
sha3 = "0.10"
array-init = "2.0.0"
bus-mapping = { path = "../bus-mapping" }
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
ethers-core = "1.0.2"
ethers-signers = { version = "1.0.2", optional = true }
mock = { path = "../mock", optional = true }
strum = "0.24"
strum_macros = "0.24"
rand_xorshift = "0.3"
rand = "0.8"
itertools = "0.10.3"
lazy_static = "1.4"
mpt-zktrie = { path = "../zktrie" }
keccak256 = { path = "../keccak256"}
log = "0.4"
env_logger = "0.9"

halo2_base = { git = "https://github.com/scroll-tech/halo2-lib", branch = "halo2-ecc-ecdsa-0129", default-features = false }
halo2_ecc = { git = "https://github.com/scroll-tech/halo2-lib", branch = "halo2-ecc-ecdsa-0129", default-features = false }

maingate = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", tag = "v2023_02_02" }

libsecp256k1 = "0.7"
num-bigint = { version = "0.4" }
subtle = "2.4"
rand_chacha = "0.3"
snark-verifier = { git = "https://github.com/privacy-scaling-explorations/snark-verifier", tag = "v2023_02_02", default-features = false, features = ["loader_halo2", "system_halo2"] }
hex = "0.4.3"
rayon = "1.5"
once_cell = "1.17.0"

[dev-dependencies]
ark-std = { version = "0.3", features = ["print-trace"] }
bus-mapping = { path = "../bus-mapping", features = ["test"] }
criterion = "0.3"
ctor = "0.1.22"
ethers-signers = "1.0.2"
hex = "0.4.3"
itertools = "0.10.1"
mock = { path = "../mock" }
pretty_assertions = "1.0.0"

[features]
default = ["test", "test-circuits"]
test = ["ethers-signers", "mock"]
test-circuits = []
warn-unimplemented = ["eth-types/warn-unimplemented"]
onephase = []
zktrie = []
enable-sign-verify = []
codehash = []
reject-eip2718 = []
poseidon-codehash = []
scroll = []
